version: '3.7'

services:
  bot:
    container_name: crypto-trading-bot-quant
    image: node:10
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
        - "8081:8081"
    command: npm start
